<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
		<TargetFramework>net6.0-windows7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PlatformTarget>x64</PlatformTarget>
		<Platforms>x64</Platforms>
		<LangVersion>preview</LangVersion>
		<AssemblyName>Minotaur.Painter</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Minotaur.Boards\Minotaur.Boards.csproj" />
    <ProjectReference Include="..\Minotaur.Utils\Minotaur.Utils.csproj" />
  </ItemGroup>

</Project>
