<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows7.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <LangVersion>preview</LangVersion>
	  <ErrorReport>none</ErrorReport>
    <AssemblyName>Minotaur.1</AssemblyName>
    <PackageId>Minotaur</PackageId>
    <Authors />
    <ApplicationIcon />
    <StartupObject />
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Difficulty\**" />
    <Compile Remove="Legacy\**" />
    <EmbeddedResource Remove="Difficulty\**" />
    <EmbeddedResource Remove="Legacy\**" />
    <None Remove="Difficulty\**" />
    <None Remove="Legacy\**" />
  </ItemGroup>
  <ItemGroup>
    <None Update="ExperimentData\2020.07.15 Sebastian.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ExperimentData\2020.07.18 Sebastian.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ExperimentData\2020.01.04 Sebastian.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ExperimentData\2020.08.11 Chi.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ExperimentData\2020.08.11 Sebastian.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ExperimentData\2020.08.14 Sebastian.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ExperimentData\2021.03.01 Sebastian.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ExperimentData\2021.03.14 Sebastian.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ExperimentData\all_7x6.tsv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="gfx\board_cell_closed2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="gfx\board_cell_open.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="gfx\board_cell_closed3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="gfx\board_cell_open2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ExperimentData\sebastian665.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ANSI.Console" Version="2.5.0" />
    <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.0.0" />
    <PackageReference Include="FlexLabs.EntityFrameworkCore.Upsert" Version="6.0.1" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="MathNet.Numerics.MKL.Win-x64" Version="3.0.0" />
    <PackageReference Include="MathNet.Numerics.OpenBLAS.Win" Version="0.2.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.4" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Drawing.Common" Version="6.0.0" />
    <PackageReference Include="ZstdSharp.Port" Version="0.6.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Minotaur.Boards\Minotaur.Boards.csproj" />
    <ProjectReference Include="..\Minotaur.ExactCover\Minotaur.ExactCover.csproj" />
    <ProjectReference Include="..\Minotaur.GenericTreeSearch\Minotaur.GenericTreeSearch.csproj" />
    <ProjectReference Include="..\Minotaur.Utils\Minotaur.Utils.csproj" />
  </ItemGroup>
</Project>
